# Generated by Django 5.2.7 on 2025-11-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
    ]
