# Generated by Django 5.2.7 on 2025-11-07 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_country'),
        ('jobPosting', '0002_remove_job_country_remove_job_type_job_is_remote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_max',
        ),
        migrations.AddField(
            model_name='job',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Customer Service', 'Customer Service'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources'), ('Management', 'Management'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Executive', 'Executive')], default='Entry Level', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='business.business'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
