# Generated by Django 4.2.6 on 2025-11-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0003_alter_job_options_rename_salary_job_salary_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
