# Generated by Django 4.2.6 on 2025-11-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_country'),
        ('jobPosting', '0004_remove_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.category'),
            preserve_default=False,
        ),
    ]
